package main

// **** DO NOT EDIT ****
// 
// This file is auto-generated by scripts/get-aws-env.sh.

const AWS_COGNITO_REGION = "us-east-1"
const AWS_COGNITO_USER_POOL_ID = "us-east-1_hyOWP6bHf"

const CLIENT_ID = "5anhhrck2mc9t5bbfd5nho4fij"
const CLIENT_SECRET = "1tq5jc8j0esch2hojlnlfvad34siicirklao2065ad70ptcaquhf"
const AUTH_URL = "https://mycsdev.auth.us-east-1.amazoncognito.com/login"
const TOKEN_URL = "https://mycsdev.auth.us-east-1.amazoncognito.com/oauth2/token"
const USER_INFO_URL = "https://mycsdev.auth.us-east-1.amazoncognito.com/oauth2/userInfo"

const AWS_APPSYNC_REGION = "us-east-1"
const AWS_USERSPACE_API_URL = "https://ss3hvtbnzrasfbevhaoa4mlaiu.appsync-api.us-east-1.amazonaws.com/graphql"
